name: pandaraShop
version: '${project.version}'
main: pandaraShop.Main
api-version: 1.19
authors: [ CheekyPandaBoy ]
description: A shop plugin for Pandara
softdepend:
  - WorldGuard
  - Shopkeepers
commands:
  shop:
    description: General shop command. It must be followed by an option.
  shopworld:
    description: Teleports the player to the shop world.
